### ISSUE TITLE
Couldn't create connection to server

### ISSUE THREAD

**Issue by chengstark** [oliversen/chatgpt-docstrings#6]
2024-06-07 12:41:18.389 [info] [Error - 12:41:18 PM] ChatGPT: Docstring Generator client: couldn't create connection to server.
2024-06-07 12:41:18.389 [info] Error: command 'chatgpt-docstrings.applyGenerate' already exists

I got these two errors, how to resolve this?

**Comment by chengstark** [comment]
a more detailed log is:

`024-06-07 12:46:43.867 [info] Server run command: /bin/python3 /home/users/zg78/.vscode-server/extensions/oliversen.chatgpt-docstrings-0.7.1/bundled/lsp_server/_start.py
2024-06-07 12:46:43.867 [info] Server: Start requested.
2024-06-07 12:46:45.202 [info] CWD Server: /usr/project/xtmp/zg78/proto_proj
2024-06-07 12:46:45.203 [info] PID Server: 2375014
2024-06-07 12:46:45.203 [info] sys.path used to run Server:
   /home/users/zg78/.vscode-server/extensions/oliversen.chatgpt-docstrings-0.7.1/bundled/libs{os.linesep}   /home/users/zg78/.vscode-server/extensions/oliversen.chatgpt-docstrings-0.7.1/bundled/lsp_server{os.linesep}   /usr/lib/python310.zip{os.linesep}   /usr/lib/python3.10{os.linesep}   /usr/lib/python3.10/lib-dynload{os.linesep}   /usr/local/lib/python3.10/dist-packages{os.linesep}   /usr/lib/python3/dist-packages
2024-06-07 12:46:45.203 [info] Global settings:
{
    "cwd": "/home/users/zg78",
    "workspace": "/home/users/zg78",
    "interpreter": [],
    "openaiModel": "gpt-4",
    "docstringFormat": "google",
    "onNewLine": true,
    "promptPattern": "Create docstring in {docstring_format} format for python function below:\n{function}",
    "responseTimeout": 30,
    "showProgressNotification": true
}

2024-06-07 12:46:45.203 [info] Settings used to run Server:
{
    "/usr/xtmp/zg78/proto_proj": {
        "cwd": "/usr/xtmp/zg78/proto_proj",
        "workspace": "file:///usr/xtmp/zg78/proto_proj",
        "interpreter": [
            "/bin/python3"
        ],
        "openaiModel": "gpt-4",
        "docstringFormat": "google",
        "onNewLine": true,
        "promptPattern": "Create docstring in {docstring_format} format for python function below:\n{function}",
        "responseTimeout": 30,
        "showProgressNotification": true,
        "workspaceFS": "/usr/xtmp/zg78/proto_proj"
    }
}

2024-06-07 12:46:45.206 [info] [Error - 12:46:45 PM] Server initialization failed.
2024-06-07 12:46:45.206 [info] Error: command 'chatgpt-docstrings.applyGenerate' already exists
	at h.registerCommand (/home/users/zg78/.vscode-server/cli/servers/Stable-89de5a8d4d6205e5b11647eb6a74844ca23d2573/server/out/vs/workbench/api/node/extensionHostProcess.js:155:199080)
	at Object.registerCommand (/home/users/zg78/.vscode-server/cli/servers/Stable-89de5a8d4d6205e5b11647eb6a74844ca23d2573/server/out/vs/workbench/api/node/extensionHostProcess.js:165:21945)
	at t.ExecuteCommandFeature.register (/home/users/zg78/.vscode-server/extensions/oliversen.chatgpt-docstrings-0.7.1/dist/extension.js:2:799538)
	at t.ExecuteCommandFeature.initialize (/home/users/zg78/.vscode-server/extensions/oliversen.chatgpt-docstrings-0.7.1/dist/extension.js:2:799117)
	at S.initializeFeatures (/home/users/zg78/.vscode-server/extensions/oliversen.chatgpt-docstrings-0.7.1/dist/extension.js:2:749635)
	at S.doInitialize (/home/users/zg78/.vscode-server/extensions/oliversen.chatgpt-docstrings-0.7.1/dist/extension.js:2:736449)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async S.start (/home/users/zg78/.vscode-server/extensions/oliversen.chatgpt-docstrings-0.7.1/dist/extension.js:2:733464)
	at async t.restartServer (/home/users/zg78/.vscode-server/extensions/oliversen.chatgpt-docstrings-0.7.1/dist/extension.js:2:653816)
	at async /home/users/zg78/.vscode-server/extensions/oliversen.chatgpt-docstrings-0.7.1/dist/extension.js:2:661150
	at async h (/home/users/zg78/.vscode-server/cli/servers/Stable-89de5a8d4d6205e5b11647eb6a74844ca23d2573/server/out/vs/workbench/api/node/extensionHostProcess.js:155:200466)
2024-06-07 12:46:45.206 [info] [Error - 12:46:45 PM] ChatGPT: Docstring Generator client: couldn't create connection to server.
2024-06-07 12:46:45.206 [info] Error: command 'chatgpt-docstrings.applyGenerate' already exists
	at h.registerCommand (/home/users/zg78/.vscode-server/cli/servers/Stable-89de5a8d4d6205e5b11647eb6a74844ca23d2573/server/out/vs/workbench/api/node/extensionHostProcess.js:155:199080)
	at Object.registerCommand (/home/users/zg78/.vscode-server/cli/servers/Stable-89de5a8d4d6205e5b11647eb6a74844ca23d2573/server/out/vs/workbench/api/node/extensionHostProcess.js:165:21945)
	at t.ExecuteCommandFeature.register (/home/users/zg78/.vscode-server/extensions/oliversen.chatgpt-docstrings-0.7.1/dist/extension.js:2:799538)
	at t.ExecuteCommandFeature.initialize (/home/users/zg78/.vscode-server/extensions/oliversen.chatgpt-docstrings-0.7.1/dist/extension.js:2:799117)
	at S.initializeFeatures (/home/users/zg78/.vscode-server/extensions/oliversen.chatgpt-docstrings-0.7.1/dist/extension.js:2:749635)
	at S.doInitialize (/home/users/zg78/.vscode-server/extensions/oliversen.chatgpt-docstrings-0.7.1/dist/extension.js:2:736449)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async S.start (/home/users/zg78/.vscode-server/extensions/oliversen.chatgpt-docstrings-0.7.1/dist/extension.js:2:733464)
	at async t.restartServer (/home/users/zg78/.vscode-server/extensions/oliversen.chatgpt-docstrings-0.7.1/dist/extension.js:2:653816)
	at async /home/users/zg78/.vscode-server/extensions/oliversen.chatgpt-docstrings-0.7.1/dist/extension.js:2:661150
	at async h (/home/users/zg78/.vscode-server/cli/servers/Stable-89de5a8d4d6205e5b11647eb6a74844ca23d2573/server/out/vs/workbench/api/node/extensionHostProcess.js:155:200466)
2024-06-07 12:46:45.206 [error] Server: Start failed: Error: command 'chatgpt-docstrings.applyGenerate' already exists
2024-06-07 12:46:45.206 [info] [Error - 12:46:45 PM] Sending document notification textDocument/didOpen failed
2024-06-07 12:46:45.206 [info] Error: command 'chatgpt-docstrings.applyGenerate' already exists
	at h.registerCommand (/home/users/zg78/.vscode-server/cli/servers/Stable-89de5a8d4d6205e5b11647eb6a74844ca23d2573/server/out/vs/workbench/api/node/extensionHostProcess.js:155:199080)
	at Object.registerCommand (/home/users/zg78/.vscode-server/cli/servers/Stable-89de5a8d4d6205e5b11647eb6a74844ca23d2573/server/out/vs/workbench/api/node/extensionHostProcess.js:165:21945)
	at t.ExecuteCommandFeature.register (/home/users/zg78/.vscode-server/extensions/oliversen.chatgpt-docstrings-0.7.1/dist/extension.js:2:799538)
	at t.ExecuteCommandFeature.initialize (/home/users/zg78/.vscode-server/extensions/oliversen.chatgpt-docstrings-0.7.1/dist/extension.js:2:799117)
	at S.initializeFeatures (/home/users/zg78/.vscode-server/extensions/oliversen.chatgpt-docstrings-0.7.1/dist/extension.js:2:749635)
	at S.doInitialize (/home/users/zg78/.vscode-server/extensions/oliversen.chatgpt-docstrings-0.7.1/dist/extension.js:2:736449)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async S.start (/home/users/zg78/.vscode-server/extensions/oliversen.chatgpt-docstrings-0.7.1/dist/extension.js:2:733464)
	at async t.restartServer (/home/users/zg78/.vscode-server/extensions/oliversen.chatgpt-docstrings-0.7.1/dist/extension.js:2:653816)
	at async /home/users/zg78/.vscode-server/extensions/oliversen.chatgpt-docstrings-0.7.1/dist/extension.js:2:661150
	at async h (/home/users/zg78/.vscode-server/cli/servers/Stable-89de5a8d4d6205e5b11647eb6a74844ca23d2573/server/out/vs/workbench/api/node/extensionHostProcess.js:155:200466)
`

**Comment by oliversen** [comment]
Thanks for your feedback! Please write a Python and VSCode version. And what operating system are you using?
